language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -r hass_host_sensors/requirements.txt

script: coverage run hass_host_sensors/tests.py
after_success: bash <(curl -s https://codecov.io/bash)